version: '3'
services:
  main:
    build: EnergyPlusExample
    network_mode: host
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./EnergyPlusExample:/app